export const Pokemons = [
    {
    id: "#304",
    name: "Aron",
    color: "#B7B9D0",
    image: "/img/aron.png",
    tips: "Steel", 
    tips2: "Rock",
    weight: "60,0kg",
    height: "0,4",
    moves: "Sturdy", 
    moves2: "Rock-Head",
    description: "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that protects its body.",
    HP: "050",
    ATK: "070",
    DEF: "100",
    SATK: "040",
    SDEF: "040",
    SPD: "030"
    },
    {
    id: "#001",
    name: "Bulbasaur",
    color: "#74CB48",
    image: "/img/bulbasaur.png",
    tips: "Gross", 
    tips2: "Poison",
    weight: "6,9kg",
    height: "0,7",
    moves: "Chiorophyll", 
    moves2: "Overgrow",
    description: "There is a plant seed on its back right from the doy this Pokemon is born. The seed slowly grows larger.",
    HP: "045",
    ATK: "049",
    DEF: "049",
    SATK: "065",
    SDEF: "065",
    SPD: "045"
    },
    {
    id: "#012",
    name: "Butterfree",
    color: "#A7B723",
    image: "/img/butterfree.png",
    tips: "Bug", 
    tips2: "Flying",
    weight: "32,0kg",
    height: "1,1m",
    moves: "Compound-Eyes", 
    moves2: "Tinted-Lens",
    description: "In battle, it flaps its wings at great speed to release highly toxic dust into the air",
    HP: "060",
    ATK: "045",
    DEF: "050",
    SATK: "090",
    SDEF: "080",
    SPD: "070"
    },
    {
    id: "#004",
    name: "charmander",
    color: "#F57D31",
    image: "/img/charmander.png",
    tips: "Fire",
    weight: "8,5kg",
    height: "0,6m",
    moves: "Mega-Punch", 
    moves2: "Fire-Punch",
    description: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
    HP: "039",
    ATK: "052",
    DEF: "043",
    SATK: "060",
    SDEF: "050",
    SPD: "065"
    },
    {
    id: "#132",
    name: "Ditto",
    color: "#AAA67F",
    image: "/img/ditto.png",
    tips: "Normal",
    weight: "4,0kg",
    height: "0,3m",
    moves: "Limber",
    moves2: "Imposter", 
    description: "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
    HP: "048",
    ATK: "048",
    DEF: "048",
    SATK: "048",
    SDEF: "048",
    SPD: "048"
    },
    {
    id: "#092",
    name: "Gastly",
    color: "#70559B",
    image: "/img/gastly.png",
    tips: "Ghost",
    tips2: "Type",
    weight: "0,1kg",
    height: "1,3m",
    moves: "Levitate",
    description: "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poisan.",
    HP: "030",
    ATK: "035",
    DEF: "030",
    SATK: "100",
    SDEF: "035",
    SPD: "080"
    },
    {
    id: "#152",
    name: "Mew",
    color: "#FB5584",
    image: "/img/mew.png",
    tips: "Paychic",
    weight: "4,0kg",
    height: "0,4m",
    moves: "Synchronize",
    description: "When viewed throungh a microscope, this Pokemon's short, fine, delicate hair can be seen.",
    HP: "100",
    ATK: "100",
    DEF: "100",
    SATK: "100",
    SDEF: "100",
    SPD: "100"
    },
    {
    id: "#025",
    name: "Pikachu",
    color: "#F9CF30",
    image: "/img/pikachu.png",
    tips: "Electric",
    weight: "6,0kg",
    height: "0,4m",
    moves: "Mega-Punch",
    moves2: "Pay-Day",
    description: "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.",
    HP: "035",
    ATK: "055",
    DEF: "040",
    SATK: "050",
    SDEF: "050",
    SPD: "090",
    },
    {
    id: "#007",
    name: "Squirtle",
    color: "#6493EB",
    image: "/img/squirtle.png",
    tips: "Water",
    weight: "9.0kg",
    height: "0,5m",
    moves: "Torrent",
    moves2: "Rain-Dish",
    description: "when it retracts its long neck into its shell, it squirts out water with vigorous force.",
    HP: "044",
    ATK: "048",
    DEF: "065",
    SATK: "050",
    SDEF: "065",
    SPD: "043"
    }
    ];