export const Pokemons = [
    {
    id: "304",
    name: "Aron",
    color: "#B7B9D0",
    secondaryColor: "#B69E31",
    image: "/img/aron.png",
    type: "Steel", 
    type2: "Rock",
    weight: "60,0kg",
    height: "0,4",
    ability: "Sturdy", 
    ability2: "Rock-Head",
    description: "It eats iron ore - and sometimes railroad tracks - to build up the steel armor that protects its body.",
    stats: {
       HP: "050",
       ATK: "070",
       DEF: "100",
       STAK: "040",
       SDEF: "040",
       SPD: "030",
     }
    },
    {
    id: "001",
    name: "Bulbasaur",
    color: "#74CB48",
    secondaryColor: "rgb(168, 145, 236)",
    image: "/img/bulbasaur.png",
    type: "Gross", 
    type2: "Poison",
    weight: "6,9kg",
    height: "0,7",
    ability: "Chiorophyll", 
    ability2: "Overgrow",
    description: "There is a plant seed on its back right from the doy this Pokemon is born. The seed slowly grows larger.",
    stats: {
        HP: "045",
        ATK: "049",
        DEF: "049",
        STAK: "065",
        SDEF: "065",
        SPD: "045"
    }
    },
    {
    id: "012",
    name: "Butterfree",
    color: "#A7B723",
    secondaryColor: "#A891EC",
    image: "/img/butterfree.png",
    type: "Bug", 
    type2: "Flying",
    weight: "32,0kg",
    height: "1,1m",
    ability: "Compound-Eyes", 
    ability2: "Tinted-Lens",
    description: "In battle, it flaps its wings at great speed to release highly toxic dust into the air",
    stats: {
        HP: "060",
        ATK: "045",
        DEF: "050",
        STAK: "090",
        SDEF: "080",
        SPD: "070",
    }
    },
    {
    id: "004",
    name: "charmander",
    color: "#F57D31",
    secondaryColor: "",
    image: "/img/charmander.png",
    type: "Fire",
    type2: "",
    weight: "8,5kg",
    height: "0,6m",
    ability: "Mega-Punch", 
    ability2: "Fire-Punch",
    description: "It has a preference for hot things. When it rains, steam is said to spout from the tip of its tail.",
    stats: { 
        HP: "039",
        ATK: "052",
        DEF: "043",
        STAK: "060",
        SDEF: "050",
        SPD: "065",
    }
    },
    {
    id: "132",
    name: "Ditto",
    color: "#AAA67F",
    secondaryColor: "",
    image: "/img/ditto.png",
    type: "Normal",
    type2: "",
    weight: "4,0kg",
    height: "0,3m",
    ability: "Limber",
    ability2: "Imposter", 
    description: "It can reconstitute its entire cellular structure to change into what it sees, but it returns to normal when it relaxes.",
    stats: {
        HP: "048",
        ATK: "048",
        DEF: "048",
        STAK: "048",
        SDEF: "048",
        SPD: "048"
    }
    },
    {
    id: "092",
    name: "Gastly",
    color: "#70559B",
    secondaryColor: "#A43E9E",
    image: "/img/gastly.png",
    type: "Ghost",
    type2: "Type",
    weight: "0,1kg",
    height: "1,3m",
    ability: "Levitate",
    ability2: "",
    description: "Born from gases, anyone would faint if engulfed by its gaseous body, which contains poisan.",
    stats: { 
        HP: "030",
        ATK: "035",
        DEF: "030",
        STAK: "100",
        SDEF: "035",
        SPD: "080",
    }
    },
    {
    id: "152",
    name: "Mew",
    color: "#FB5584",
    secondaryColor: "",
    image: "/img/mew.png",
    type: "Paychic",
    type2: "",
    weight: "4,0kg",
    height: "0,4m",
    ability: "Synchronize",
    ability2: "",
    description: "When viewed throungh a microscope, this Pokemon's short, fine, delicate hair can be seen.",
    stats: { 
        HP: "100",
        ATK: "100",
        DEF: "100",
        STAK: "100",
        SDEF: "100",
        SPD: "100",
    }
    },
    {
    id: "025",
    name: "Pikachu",
    color: "#F9CF30",
    secondaryColor: "",
    image: "/img/pikachu.png",
    type: "Electric",
    type2: "",
    weight: "6,0kg",
    height: "0,4m",
    ability: "Mega-Punch",
    ability2: "Pay-Day",
    description: "Pikachu that can generate powerful electricity have cheek sacs that are extra soft and super stretchy.",
    stats: {
        HP: "035",
        ATK: "055",
        DEF: "040",
        STAK: "050",
        SDEF: "050",
        SPD: "090",
     }
     },
    {
    id: "007",
    name: "Squirtle",
    color: "#6493EB",
    secondaryColor: "",
    image: "/img/squirtle.png",
    type: "Water",
    weight: "9.0kg",
    height: "0,5m",
    ability: "Torrent",
    ability2: "Rain-Dish",
    description: "when it retracts its long neck into its shell, it squirts out water with vigorous force.",
    stats: {
        HP: "044",
        ATK: "048",
        DEF: "065",
        STAK: "050",
        SDEF: "065",
        SPD: "043"
    }
    }
    ];